name: Telegram Bot Runner
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante baad restart hoga taake band na ho
  workflow_dispatch: # Button se chalane ke liye

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install python-telegram-bot pandas

      - name: Start Bot
        run: python bot.py
        timeout-minutes: 350 # Ek session takreeban 6 ghante chalega
